# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'EcommerceDemo' do

pod 'Alamofire'
pod 'AlamofireObjectMapper'
pod 'AlamofireDomain'
pod 'AlamofireImage'
pod 'DrawerController'
pod "PKHUD"
#pod 'SQLite.swift', '~> 0.10'
#pod 'Kingfisher', '~> 2.0'
#pod 'IQKeyboardManagerSwift'
#pod 'GoogleMaps', '~> 1.12'
#pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift'
#pod 'Fabric', '~> 1.6'
#pod 'Crashlytics', '~> 3.7'
#pod 'AWSS3', '2.3.0'
#pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
#pod 'Mixpanel'

end
